pipeline {
    agent any
    options{
        timeout(time: 5, unit: 'MINUTES')
        disableConcurrentBuilds()
        retry(3)
    }
    parameters {
        string(name: 'NAME', defaultValue: 'Durga', description: 'Please enter your name')

        text(name: 'EDUCATION', defaultValue: '', description: 'Please provide your background')

        booleanParam(name: 'TOGGLE', defaultValue: false, description: 'Select your answer')

        choice(name: 'SELECT', choices: ['dev', 'qa', 'uat'], description: 'Select your choices')

        password(name: 'PASSWORD', defaultValue: 'SECRET', description: 'Enter your password')
    }

    stages{
        stage("Test"){
            steps{
                echo "Hello ${params.NAME}"
                echo "Biography: ${params.EDUCATION}"
                echo "Toggle: ${params.TOGGLE}"
                echo "Choice: ${params.SELECT}"
                echo "password: ${params.PASSWORD}"
            }
        }
    }
    post{
        always{
            deleteDir()
            echo "This is will run every build"
        }
        success{
            echo "This action runs only when build is success"
        }
        failure{
            echo "This action will run when build fail"
        }
    }
}