pipeline {
    agent any
    options{
        timeout(time: 5, unit: 'MINUTES')
        disableConcurrentBuilds()
        retry(3)
    }
    parameters {
        string(name: 'PERSON', defaultValue: 'Durga', description: 'Who should I say hello to?')

        text(name: 'BIOGRAPHY', defaultValue: '', description: 'Enter some information about the person')

        booleanParam(name: 'TOGGLE', defaultValue: true, description: 'Toggle this value')

        choice(name: 'CHOICE', choices: ['One', 'Two', 'Three'], description: 'Select your choices')

        password(name: 'PASSWORD', defaultValue: 'SECRET', description: 'Enter a password')
    }

    stages{
        stage("Test"){
            steps{
                echo "Hello ${params.$PERSON}"
                echo "Biography: ${params.BIOGRAPHY}"
                echo "Toggle: ${params.TOGGLE}"
                echo "Choice: ${params.CHOICE}"
                echo "password: ${params.PASSWORD}"
            }
        }
    }

    post{
        always{
            deleteDir()
            echo "This is will run every build"
        }
        success{
            echo "This action runs only when build is success"
        }
        failure{
            echo "This action will run when build fail"
        }
    }
}