pipeline {
    agent any
    options{
        timeout(time: 5, unit: 'MINUTES')
        disableConcurrentBuilds()
        retry(3)
    }
    stages{
        stage("Test"){
            steps{
                echo "This is test stage"
            }
        }
        stage("Build"){
            steps{
                echo "This is Build Stage"
                // sh 'sleep 10'
            }   error 'pipeline failed'
        }
        stage("Deploy"){
            steps{
                echo "This is Deploy stage"
            }
        }
    }

    post{
        always{
            deleteDir()
            echo "This is will run every build"
        }
        success{
            echo "This action runs only when build is success"
        }
        failure{
            echo "This action will run when build fail"
        }
    }
}