pipeline {
    agent any
    stages{
        stage("Test"){
            steps{
                sh "echo This is test stage"
            }
        }
        stage("Build"){
            steps{
                sh "echo This is Build Stage"
            }
        }
        stage("Deploy"){
            steps{
                sh "echo This is Deploy stage"
            }
        }
    }

    post{
        always{
            deleteDir()
            echo "This is will run every build"
        }
        success{
            echo "This action runs only when build is success"
        }
        failure{
            echo "This action will run when build fail"
        }
    }
}